//go:build codegen

// Package tools holds guards that exec the proto toolchain.
//
// Everything here is behind the `codegen` build tag because it needs the network (to
// resolve buf on a cold module cache) and takes tens of seconds. Keeping it out of the
// default tier is what lets `go test ./...` stay fast and offline.
//
// Run with: go tool task verify:codegen
package tools

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/example/gomicro/internal/testutil"
)

// bufPin must match Taskfile.yml and .github/workflows/ci.yml.
// test/toolpins_test.go asserts all three are identical.
const bufPin = "github.com/bufbuild/buf/cmd/buf@v1.72.0"

// generatedSuffixes are the files buf owns. Anything else under gen/ is not compared,
// because a hand-written file living there would make byte-equality impossible by
// construction -- which is exactly why internal/protoschema/descriptor_test.go lives
// outside gen/ rather than inside it.
var generatedSuffixes = []string{".pb.go", "_grpc.pb.go", ".pb.gw.go"}

// TestGeneratedCodeIsUpToDate is the gate that makes committing generated code safe.
//
// Committing gen/ is what allows `git clone && go build ./...` to work with no codegen
// step, no protoc and no network -- the property the whole template is built around. The
// cost is that the committed output can silently drift from the .proto files.
//
// This closes that: it regenerates into a temp directory and byte-compares. Someone who
// edits a proto and forgets to run `task gen` gets a failure naming the exact file.
func TestGeneratedCodeIsUpToDate(t *testing.T) {
	root := testutil.RepoRoot(t)
	tmp := t.TempDir()

	cmd := exec.Command("go", "run", bufPin, "generate", "--template", "buf.gen.yaml", "-o", tmp)
	cmd.Dir = root
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("buf generate: %v\n%s", err, out)
	}

	committed := collectGenerated(t, filepath.Join(root, "gen"))
	fresh := collectGenerated(t, filepath.Join(tmp, "gen"))

	for path, freshBody := range fresh {
		committedBody, ok := committed[path]
		if !ok {
			t.Errorf("gen/%s was generated but is not committed.\nRun: go tool task gen", path)
			continue
		}
		if committedBody != freshBody {
			t.Errorf("gen/%s is stale -- the .proto has changed since it was generated.\n"+
				"Run: go tool task gen", path)
		}
		delete(committed, path)
	}

	for path := range committed {
		t.Errorf("gen/%s is committed but is no longer generated by any proto.\n"+
			"Delete it, then run: go tool task gen", path)
	}
}

// collectGenerated reads every generated file under dir, keyed by its path relative to dir.
func collectGenerated(t *testing.T, dir string) map[string]string {
	t.Helper()

	out := map[string]string{}
	err := filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if !isGenerated(path) {
			return nil
		}
		b, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}

		// Normalize line endings before comparing.
		//
		// buf writes LF into the temp directory, while the working tree may hold CRLF if
		// .gitattributes is ever weakened or a contributor's editor rewrites a file.
		// Without this the test fails on Windows for a reason that has nothing to do with
		// the protos, which is precisely the undiagnosable failure the template must avoid.
		out[filepath.ToSlash(rel)] = strings.ReplaceAll(string(b), "\r\n", "\n")
		return nil
	})
	if err != nil {
		t.Fatalf("walk %s: %v", dir, err)
	}
	return out
}

func isGenerated(path string) bool {
	for _, suffix := range generatedSuffixes {
		if strings.HasSuffix(path, suffix) {
			return true
		}
	}
	return false
}
